"""Initial Migration

Revision ID: 244342b0cc6a
Revises: 
Create Date: 2025-03-24 19:38:28.362739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244342b0cc6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forums',
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('forum_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('forum_id')
    )
    op.create_index(op.f('ix_forums_forum_id'), 'forums', ['forum_id'], unique=False)
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('analysis_mode', sa.Enum('auto', 'on_demand', name='analysis_mode_enum'), nullable=True),
    sa.Column('weight_data', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index(op.f('ix_stocks_stock_id'), 'stocks', ['stock_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_portfolios_portfolio_id'), 'portfolios', ['portfolio_id'], unique=False)
    op.create_table('sentiment_analysis',
    sa.Column('sentiment_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_value', sa.Float(), nullable=False),
    sa.Column('raw_string', sa.Text(), nullable=True),
    sa.Column('weight_data', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sentiment_id')
    )
    op.create_index(op.f('ix_sentiment_analysis_sentiment_id'), 'sentiment_analysis', ['sentiment_id'], unique=False)
    op.create_table('threads',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forum_id'], ['forums.forum_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_threads_thread_id'), 'threads', ['thread_id'], unique=False)
    op.create_table('user_friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'blocked', name='friend_status_enum'), server_default='pending', nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('portfolio_stocks',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'stock_id')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('post_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_url')
    )
    op.create_index(op.f('ix_posts_post_id'), 'posts', ['post_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('comment_likes',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_post_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('portfolio_stocks')
    op.drop_table('user_friends')
    op.drop_index(op.f('ix_threads_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_sentiment_analysis_sentiment_id'), table_name='sentiment_analysis')
    op.drop_table('sentiment_analysis')
    op.drop_index(op.f('ix_portfolios_portfolio_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_stock_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_forums_forum_id'), table_name='forums')
    op.drop_table('forums')
    # ### end Alembic commands ###
