"""Initial Migration


;
''


Revision ID: 75d32389bd03
Revises: 
Create Date: 2025-04-03 21:12:49.695387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75d32389bd03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis', sa.Column('entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sentiment_analysis', 'scraped_reddit_entries', ['entry_id'], ['entry_id'], ondelete='CASCADE')
    op.drop_column('sentiment_analysis', 'weight_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis', sa.Column('weight_data', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'sentiment_analysis', type_='foreignkey')
    op.drop_column('sentiment_analysis', 'entry_id')
    # ### end Alembic commands ###
