"""added rep stat to User

Revision ID: c739141bae0b
Revises: c69eebcd4ceb
Create Date: 2025-04-22 16:46:22.121305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c739141bae0b'
down_revision: Union[str, None] = 'c69eebcd4ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reputation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reputation')
    # ### end Alembic commands ###
